name: Push Docker Images CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  push-docker-images:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        images: [app, database, reverse_proxy, payment_gateway]
        
        
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get tags
        id: var
        run: echo "::set-output name=tag::$(git rev-parse --short HEAD)"
      - name: Check outputs
        run: echo ${{ steps.var.outputs.tag }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./${{matrix.images}}
          platforms: linux/amd64
          push: true
          tags: |
            ${{secrets.DOCKERHUB_USERNAME}}/atsea-sample-shop-app-${{matrix.images}}:latest
            ${{secrets.DOCKERHUB_USERNAME}}/atsea-sample-shop-app-${{matrix.images}}:${{ steps.var.outputs.tag }}